const countries = [
    "Afghanistan", "Albanie", "Algérie", "Andorre", "Angola",
    "Antigua-et-Barbuda", "Argentine", "Arménie", "Australie",
    "Autriche", "Azerbaïdjan", "Bahamas", "Bahreïn", "Bangladesh",
    "Barbade", "Biélorussie", "Belgique", "Belize", "Bénin",
    "Bhoutan", "Bolivie", "Bosnie-Herzégovine", "Botswana",
    "Brésil", "Brunei", "Bulgarie", "Burkina Faso", "Burundi",
    "Cabo Verde", "Cambodge", "Cameroun", "Canada", "Centrafrique",
    "Chili", "Chine", "Chypre", "Colombie", "Comores",
    "Congo", "Costa Rica", "Croatie", "Cuba", "Danemark",
    "Djibouti", "Dominique", "Égypte", "El Salvador", "Émirats arabes unis",
    "Équateur", "Érythrée", "Espagne", "Estonie", "Eswatini",
    "États-Unis", "Fidji", "Finlande", "France", "Gabon",
    "Gambie", "Géorgie", "Allemagne", "Ghana", "Grèce",
    "Grenade", "Guatemala", "Guinée", "Guinée-Bissau", "Guinée équatoriale",
    "Guyana", "Honduras", "Hongrie", "Islande", "Inde",
    "Indonésie", "Irak", "Iran", "Irlande", "Islande",
    "Italie", "Jamaïque", "Japon", "Jordanie", "Kazakhstan",
    "Kenya", "Kirghizistan", "Kiribati", "Koweït", "Laos",
    "Lettonie", "Liban", "Liberia", "Libye", "Lituanie",
    "Luxembourg", "Madagascar", "Malaisie", "Malawi", "Maldives",
    "Mali", "Malte", "Maroc", "Maurice", "Mauritanie",
    "Mexique", "Micronésie", "Moldavie", "Monaco", "Mongolie",
    "Mozambique", "Namibie", "Nauru", "Népal", "Nicaragua",
    "Niger", "Nigeria", "Norvège", "Nouvelle-Zélande", "Oman",
    "Pakistan", "Palaos", "Panama", "Papouasie-Nouvelle-Guinée", "Paraguay",
    "Pays-Bas", "Pérou", "Philippines", "Pologne", "Portugal",
    "Qatar", "République centrafricaine", "République tchèque", "Roumanie", "Royaume-Uni",
    "Rwanda", "Samoa", "Saint-Kitts-et-Nevis", "Saint-Vincent-et-les-Grenadines", "Sénégal",
    "Serbie", "Seychelles", "Sierra Leone", "Singapour", "Slovénie",
    "Slovénie", "Somalie", "Soudan", "Soudan du Sud", "Sri Lanka",
    "Suède", "Suisse", "Syrie", "Tadjikistan", "Tanzanie",
    "Tchad", "Thaïlande", "Togo", "Tonga", "Trinité-et-Tobago",
    "Tunisie", "Turkménistan", "Turquie", "Vanuatu", "Vatican",
    "Venezuela", "Viêt Nam", "Yémen", "Zambie", "Zimbabwe"
];

export default countries;